language: python
python:
  - "3.6"  # 3.6
# command to install dependencies
env:
  - DJANGO=2.1.2
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python manage.py test
